module.exports = Object.freeze({
    CODE_INTERNAL_SERVER_ERROR: 500,
    CODE_FORBIDDEN: 403,
    CODE_UNAUTHORIZED: 401,
    CODE_BAD_REQUEST: 400,
    CODE_SUCCESS: 200,
    CODE_NOTFOUND: 404,
});